[tool.poetry]
name = "survey"
version = "0.1.0"
description = ""
authors = ["Kaito Koto"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
flask = "^3.0.3"
flask-cors = "^4.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
